export const SITE_NAME = "Food Delivery"

export const SITE_URL = process.env.APP_URL as string

export const CREATOR = "svyatoslavw"

export const GITHUB_URL = "https://github.com/svyatoslavw"

export const SITE_KEYWORDS = [
  "Next.js",
  "ReactJS",
  "Javascript",
  "Typescript",
  "Web developing",
  "Food Delivery Clone",
  "Github",
  "Frontend",
  "Supabase",
  "junior frontend pet project",
  "Food delivery",
  "Online food ordering",
  "Restaurant delivery",
  "Food courier service",
  "Order food online",
  "Contactless delivery",
  "Fast food delivery",
  "Food delivery at home",
  "Ready-to-eat food delivery",
  "Delivery from restaurants",
  "Mobile food ordering app",
  "Delicious food delivery",
  "Snack delivery",
  "Takeout food",
  "Convenient food ordering",
  "Healthy food delivery",
  "Office food delivery",
  "Restaurant menu for delivery",
  "Free food delivery",
  "Local food delivery",
  "Homemade food delivery",
  "Takeaway food",
  "Round-the-clock food delivery",
  "Food delivery right now",
  "Food ordering app",
  "Quick food order",
  "Restaurant food delivery",
  "Food alternative",
  "Online ordering restaurants",
  "Free food order",
  "Popular delivery restaurants",
  "Food delivery for picnics",
  "Restaurant takeout",
  "Best delivery restaurants",
  "Delivery restaurant choices",
  "Order food anytime",
  "Restaurant delivery network",
  "Order food now",
  "Food delivery app",
  "Restaurants with wide selection",
  "Fast home food delivery",
  "Order food anytime",
  "Delivery to restaurant",
  "Ready-to-go food",
  "Best delivery restaurants",
  "Diverse menu for ordering",
  "Affordable food delivery",
  "Party food delivery",
  "Budget-friendly restaurant delivery",
  "Quality food delivery",
  "Queue-free food delivery"
]
